apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kyverno-install.yaml
  - policies/no-privilege-escalation.yaml
  - policies/image-signature-required.yaml
  - policies/networkpolicy-schema.yaml
  - policies/no-conflict-with-existing.yaml
  - policies/rbac-escalation-guard.yaml
  - policyexception-elden-system.yaml
  - policyexception-system-rbac.yaml
