import logging
from typing import Any

import yaml
from github import Github, GithubException

logger = logging.getLogger(__name__)


class GitWriter:
    def __init__(self, repo_full: str, token: str, base_branch: str, branch_prefix: str):
        if not token:
            raise RuntimeError("GitWriter requires a GitHub token")
        self.gh = Github(token)
        self.repo = self.gh.get_repo(repo_full)
        self.base = base_branch
        self.prefix = branch_prefix

    def create_defense_pr(
        self,
        incident_id: str,
        manifests: list[dict[str, Any]],
        risk: str,
        validation_summary: str,
    ) -> tuple[str, int]:
        ident = incident_id[4:] if incident_id.startswith("inc-") else incident_id
        branch = f"{self.prefix}{ident}"
        base_sha = self.repo.get_branch(self.base).commit.sha
        try:
            self.repo.create_git_ref(ref=f"refs/heads/{branch}", sha=base_sha)
        except GithubException as e:
            if e.status != 422:  # already exists
                raise
            logger.info("branch %s exists, reusing", branch)

        for idx, m in enumerate(manifests):
            kind = m.get("kind", "Resource")
            name = (m.get("metadata") or {}).get("name", f"manifest-{idx}")
            path = f"kubernetes/environments/canary/incidents/{incident_id}/{idx:02d}-{kind}-{name}.yaml"
            content = yaml.safe_dump(m, sort_keys=False)
            self._upsert_file(path, content, branch, f"defense({incident_id}): {kind}/{name}")

        title = f"defense(inc-{incident_id}): {risk} risk candidate"
        body = (
            f"Incident: `{incident_id}`\n"
            f"Risk class: **{risk}**\n\n"
            f"## Phase 3 validation\n{validation_summary}\n\n"
            f"Auto-generated by governance orchestrator. "
            f"Do not merge without reviewing policy gate results."
        )
        pr = self.repo.create_pull(title=title, body=body, head=branch, base=self.base)
        pr.add_to_labels("defense-candidate", f"risk/{risk}")
        logger.info("opened PR #%d on %s", pr.number, branch)
        return branch, pr.number

    def _upsert_file(self, path: str, content: str, branch: str, message: str) -> None:
        try:
            existing = self.repo.get_contents(path, ref=branch)
            self.repo.update_file(path, message, content, existing.sha, branch=branch)
        except GithubException as e:
            if e.status != 404:
                raise
            self.repo.create_file(path, message, content, branch=branch)
