apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argo-rollouts-install.yaml
  - analysis-template-slo.yaml
  - rollout-target-app.yaml
  - istio-virtualservice-canary.yaml
  - approval-gate-highrisk.yaml
  - rbac-rollouts.yaml
