apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd-install.yaml
  - project-elden.yaml
  - applicationset-defense-branch.yaml
  - application-shadow.yaml
  - application-prod.yaml
  - rbac-promotion-roles.yaml
