apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: elden-governance

resources:
  - governance-controller.yaml
  - ../../governance/c-deployment-control/approval-gate-highrisk.yaml
